name:                elm-ps
version:             0.1.0.0
github:              "reactormonk/elm-ps"
license:             BSD3
author:              "Simon Hafner"
maintainer:          "hafnersimon@gmail.com"
copyright:           "LGPLv3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/reactormonk/elm-ps#readme>

dependencies:
- base >= 4.7 && < 5
- purescript

# Elm dependencies
- ansi-terminal #>= 0.8 && < 0.9
- ansi-wl-pprint #>= 0.6.8 && < 0.7
- base #>=4.11 && <5
- binary #>= 0.8 && < 0.9
- bytestring #>= 0.9 && < 0.11
- connection
- containers #>= 0.5.8.2 && < 0.6
- directory #>= 1.2.3.0 && < 2.0
- edit-distance #>= 0.2 && < 0.3
- file-embed
- filelock
- filepath #>= 1 && < 2.0
- ghc-prim #>= 0.5.2
- haskeline
- HTTP #>= 4000.2.5 && < 4000.4
- http-client #>= 0.6 && < 0.7
- http-client-tls #>= 0.3 && < 0.4
- http-types #>= 0.12 && < 1.0
- language-glsl #>= 0.3
- mtl #>= 2.2.1 && < 3
- network #>= 2.4 && < 2.7
- network-bsd # breaking change
- parsec
- process
- raw-strings-qq
- scientific
- SHA
# - snap-core
# - snap-server
- template-haskell
- time #>= 1.9.1
- unordered-containers
- utf8-string
- vector
- zip-archive

library:
  source-dirs:
    - src
    - elm/compiler

executables:
  elm-ps-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-ps

tests:
  elm-ps-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-ps
